---
title: "Figure 2 (rberry)"
author: "Rebecca Hoyd"
date: "5/23/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtext)
library(ggfortify)
library(FactoMineR)
library(ggrepel)
library(ggpubr)
```

# Load data

```{r}
load("../data/figure-data/desres_rberry.rda")
load("../data/figure-data/pca_rberry.rda")
load("../data/figure-data/dist_rberry.rda")
```

# PCA

```{r}
PCA_label_plot <- 
  autoplot(rber.pca$PCA, data = rber.pca$GroupLabs, colour = "GroupID", label = FALSE, label.size = 3, shape = TRUE, frame = TRUE, frame.type = "convex") +
  theme_bw(base_size = 8.8) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  theme(
  axis.text = element_text(size = 7),
  legend.text = element_text(size = 8.8), 
  legend.title = element_blank(), 
  legend.key.size = unit(0.75, "lines"),
  legend.position = "top"
  ) +
  coord_cartesian(xlim = c(-1, 0.5), ylim = c(-0.5, 1)) +
  annotate("text", x = -0.75, y=1, label = paste0("p-value = ", rber_dist$adonis.p.val[1]))

print(PCA_label_plot)

ggsave(plot = PCA_label_plot, "../figures/pca_rberry.png", height = 2.5, width = 2)

ggsave("../figures/Fig1B-pca.svg", height= 2.5, width= 2)
ggsave("../figures/Fig1B-pca-wide.svg", height= 2.5, width= 4)
```

## Distance to centroid boxplot
```{r}
p <- rber_dist %>%
  ggplot(aes(x = GroupID, y = Distance, fill = GroupID)) +
  geom_boxplot() +
  theme_bw() +
  scale_fill_viridis_d(alpha = 0.5) +
  theme(axis.text = element_text(size = 7), 
        legend.position = "none")

p = p + stat_compare_means(method = "t.test")

ggsave(plot = p, "../figures/dist_rberry.png", height = 2.5, width =2)

ggsave("../figures/Fig1B_dist.svg", height= 2.2, width= 2)
```


# Volcano

```{r}
rber.desres %>%
  mutate(Tax.Sig=ifelse(padj < .05,TaxLev, NA),
        class.dum = ifelse(padj < 0.05, Taxa, NA),
        class.smart = if_else(grepl("g_uncl|sensu", class.dum),
                           true = NA,
                           false = class.dum),
        class.smart = str_replace(class.smart, 
                                  pattern = "_",
                                  replacement = " ")) %>%
  ggplot(aes(x=log2FoldChange,
             y=-log(padj),
             color=Tax.Sig,
             label = class.smart)) + 
  geom_point() + 
  geom_hline(yintercept = -log(0.05),
             color="red",
              linetype = "dotted",
             linewidth = 0.75) +   
  geom_vline(xintercept = c(-4,4),
             color="red",
              linetype = "dotted",
             linewidth = 0.75) + 
  guides(color=guide_legend("Taxonomic\nRank")) + 
  geom_text_repel(show.legend = FALSE, size = 6.25) + 
  theme_bw(base_size = 20) + 
  scale_color_brewer(palette="Dark2",
                     na.value="gray50",
                     breaks=c("Phylum","Class","Order","Family","Genus")) +
  theme(legend.position = c(0.97, 0.05),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color = "black", linewidth = 0.25),
        legend.box.margin = margin(2, 2, 2, 2),
        legend.text = element_text(size = 16),  
        legend.title = element_text(size = 18, hjust = 0.5) ,
        legend.key.width = unit(0.1, "cm")) +
   xlim(-8, 8)

ggsave("../figures/Fig1C.volcano.svg",
       height = 5,
       width = 7)

write_csv(rber.desres, 
          "../tables/Supp-Table-S1_rat-volcano.csv")
```
```{r}
# Define target genera for labeling
target_genera <- c("Akkermansia", "Bifidobacterium", "Lactobacillus", 
                   "Bacillus", "Enterococcus", "Ruminiclostridium_5", 
                   "Lachnospiraceae_NC2004_group", "Blautia")

rber.desres %>%
  mutate(label_this = ifelse(Taxa %in% target_genera & TaxLev == "Genus", 
                             str_replace(Taxa, "_", " "), NA)) %>%
  ggplot(aes(x = log2FoldChange, 
             y = -log(padj), 
             color = TaxLev, 
             label = label_this)) +
  geom_point() + 
  geom_text_repel(na.rm = TRUE, show.legend = FALSE, size = 6.25) +
  geom_hline(yintercept = -log(0.05), color = "red", linetype = "dotted", linewidth = 0.75) +
  geom_vline(xintercept = c(-4, 4), color = "red", linetype = "dotted", linewidth = 0.75) +
  scale_color_brewer(palette = "Dark2", na.value = "gray50",
                     breaks = c("Phylum", "Class", "Order", "Family", "Genus"),
                     name = "Taxonomic\nRank") +
  theme_bw(base_size = 20) +
  theme(legend.position = c(0.97, 0.05),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color = "black", linewidth = 0.25),
        legend.box.margin = margin(2, 2, 2, 2),
        legend.text = element_text(size = 16),  
        legend.title = element_text(size = 18, hjust = 0.5),
        legend.key.width = unit(0.1, "cm")) +
  xlim(-8, 8) +
  labs(x = "log2FoldChange", y = "-log(padj)")


```

```{r}
target_genera <- c("Akkermansia", "Bifidobacterium", "Lactobacillus", 
                   "Bacillus", "Enterococcus", "Ruminiclostridium_5", 
                   "Blautia")

rber.desres %>%
  mutate(label_this = ifelse(Taxa %in% target_genera & TaxLev == "Genus",
                             str_replace(Taxa, "_", " "), NA)) %>%
  ggplot(aes(x = log2FoldChange, 
             y = -log(padj), 
             color = log2FoldChange, 
             label = label_this)) +
  geom_point() +
  geom_text_repel(na.rm = TRUE, show.legend = FALSE, size = 6.25) +
  scale_color_viridis_c(option = "D", name = "log2FC") +  
  geom_hline(yintercept = -log(0.05), color = "red", linetype = "dotted", linewidth = 0.75) +
  geom_vline(xintercept = c(-4, 4), color = "red", linetype = "dotted", linewidth = 0.75) +
  coord_cartesian(xlim = c(-8, 8)) +
  theme_bw(base_size = 20) +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )
ggsave("../figures/Fig1C.volcano.PIRMs.svg",
       height = 5,
       width = 7)
ggsave("../figures/Fig1C.volcano.PIRMs.png",
       height = 5,
       width = 7)
```


```{r}
rber.desres %>%
  mutate(label_this = ifelse(Taxa %in% target_genera & TaxLev == "Genus", str_replace(Taxa, "_", " "), NA),
         highlight = ifelse(Taxa %in% target_genera & TaxLev == "Genus", "Target Genus", "Other")) %>%
  ggplot(aes(x = log2FoldChange, y = -log(padj), color = highlight, label = label_this)) +
  geom_point() +
  geom_text_repel(na.rm = TRUE, show.legend = FALSE, size = 6.25) +
  scale_color_manual(values = c("Target Genus" = "darkred", "Other" = "gray60")) +
  guides(color = FALSE) +
  geom_hline(yintercept = -log(0.05), color = "red", linetype = "dotted") +
  geom_vline(xintercept = c(-4, 4), color = "red", linetype = "dotted") +
  theme_bw(base_size = 20)

```

# LDA

```{r}
brb.sig <-
  rber.desres %>%
  filter(padj < .05) 


brb.sig %>% 
  mutate(Taxa = gsub("_", " ", gsub("g_", "", Taxa))) %>%
  ggplot(aes(x=log2FoldChange,
             y=reorder(Taxa,log2FoldChange),
             fill=TaxLev)) + 
  geom_bar(stat = "identity") + 
  theme_bw(base_size = 18) + 
  ggtitle("") +
  ylab("") +
  scale_fill_brewer(palette = "Dark2",
                    breaks=c("Phylum","Class","Order","Family","Genus")) +
  labs(fill = "Taxonomic\nRank") +
  theme(legend.title = element_text(size = 18, hjust = 0.5),
        legend.position = c(0.05, 0.95), 
        legend.justification = c("left", "top"),
        legend.box.just = "left",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color = "black", linewidth = 0.25),
        legend.box.margin = margin(2, 2, 2, 2),
        legend.text = element_text(size = 16),
        legend.key.width = unit(0.6, "cm")) +
  scale_y_discrete(expand = expansion(add = c(0.75, 0.75)))  


ggsave("../figures/Fig1D.effecti-size_rberry-mics.svg",
       height = 5,
       width = 7)
```










