---
title: "Figure 3 (mimic)"
author: "Rebecca Hoyd"
date: "5/23/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggtext)
library(viridis)

```

# Load data

```{r}
load("../data/figure-data/bardat_Bo_BW.rda")
load("../data/figure-data/tvol_m10.rda")
load("../data/figure-data/tvol_m1819.rda")
load("../data/figure-data/fracresponse_blautia-gavage.rda")
load("../data/figure-data/boxdat_mimic.rda")
load("../data/figure-data/longmods_mimic-heatmap.rda")
load("../data/figure-data/bardat_mimic_roseburia.rda")
```

# Barplot Blautia in samples

```{r}
Bo_abun_BW %>%
  ggplot(aes(x = timepoint, y = RelAbun)) +
  geom_bar(stat = "identity", aes(fill = timepoint), show.legend = FALSE) +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(x = "",
       y = "Relative Abundance",
       subtitle = "Blautia obeum") +
  facet_wrap(~Subject.Number, ncol = 1)

ggsave("../figures/Blautia_obeum_abundance_bar_all.png",
       height = 7.5, width = 10)

ggsave("../figures/Fig3A.svg",
       height = 7.5, width = 10)
```

# Bardat Roseburia in mimic 10 

```{r}
mim.rosebur %>%
  ggplot(aes(x=gavage.simple,y=genus_abundance,fill=treatment)) +
  geom_bar(position="dodge", stat="identity") +
  facet_wrap(. ~ timepoint) +
  labs(x = "Gavage",y = "Relative Abundance",title = "Roseburia - Mimic 10") +
  scale_fill_viridis_d() +
  theme_bw()  

ggsave("../figures/mimic10-roseburia_relabun.png", width = 7, height = 6)
```

# Tumor volume over time - mimic10

```{r}
mimic10.means %>%
  mutate(Gavage = if_else(grepl("v1", treatment.group),
                          true = "Pre-BRB",
                          false = "Post-BRB"),
         Treatment = if_else(grepl("Anti", treatment.group),
                             true = "Anti-PD1",
                             false = "IgG"),
         Gavage = fct_relevel(Gavage, c("Pre-BRB"))) %>%
  ggplot(aes(x = days.from.injection, y = mean)) +
  geom_line(aes(group = treatment.group,
                color = Gavage,
                linetype = Treatment), 
            position = position_dodge(width = .5),
            lwd = 1) + 
  geom_point(aes(color = Gavage), 
             position = position_dodge(width = .5)) +
  scale_color_viridis_d(direction = -1) + 
  geom_errorbar(aes(ymin = lwr, 
                    ymax = upr,
                    color = Gavage),
                width = 1,
                position = position_dodge(width = .5),
                lwd = 1) +
  labs(x = "Days from Tumor Injection", 
       y = expression("Tumor volume ("~mm^3~")"))  +
  theme_bw(base_size = 20)
 
ggsave("../figures/lineplot_tumorvol_mim10.png")
ggsave("../figures/Fig3C.svg")
ggsave("../figures/Fig3C-wide.svg", 
       height = 3.5, width =9)

```

```{r}
mimic10.means %>%
  mutate(Gavage = if_else(grepl("v1", treatment.group),
                          "Pre-BRB",
                          "Post-BRB"),
         Treatment = if_else(grepl("Anti", treatment.group),
                             "Anti-PD1",
                             "IgG"),
         Gavage = fct_relevel(Gavage, c("Pre-BRB"))) %>%
  ggplot(aes(x = days.from.injection, y = mean)) +
  geom_line(aes(group = treatment.group,
                color = Gavage,
                linetype = Treatment), 
            position = position_dodge(width = .5),
            lwd = 1) + 
  geom_point(aes(color = Gavage), 
             position = position_dodge(width = .5)) +
  scale_color_viridis_d(direction = -1) + 
  geom_errorbar(aes(ymin = lwr, ymax = upr, color = Gavage),
                width = 1,
                position = position_dodge(width = .5),
                lwd = 1) +
  labs(x = "Days from Tumor Injection", 
       y = expression("Tumor volume ("~mm^3~")")) +
  theme_minimal(base_size = 20) + 
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    plot.background = element_blank(), 
    axis.line = element_line()
  ) +
  scale_y_continuous(position = "right")

ggsave("../figures/Fig3C-wide.svg", 
       height = 3.5, width =9)

```


```{r}
mimic1819.means_df <- mimic1819.means$plotdat

mimic1819.means_df <- mimic1819.means_df %>%
  mutate(Supplement = factor(Supplement, levels = c("Normal", "Blautia")))

mimic1819.means_df %>%
  ggplot(aes(x = days.from.injection, y = mean)) +
  geom_line(aes(group = treatment.group,
                color = Supplement,
                linetype = Treatment), 
            linewidth = 1) + 
  geom_point(aes(color = Supplement)) +
  labs(x = "Days from Tumor Injection", 
       y = expression("Mean Tumor Volume ("~mm^3~")"),
       color = "Sample") +  
  theme_bw() +
  scale_color_manual(
    values = c("#d95f02", "#7570b3"),
    labels = c("85", "85 + Blautia")
  ) +
  scale_x_continuous(
    limits = c(0, max(mimic1819.means_df$days.from.injection) + 1)
  )

ggsave("../figures/meantumorvolume_mim1819_lineplot.png", 
       height = 5, width = 7)

ggsave("../figures/Fig3E.svg", 
       height = 3, width = 5)

```

# Fraction response - probably needs calculations checked

```{r}
mimic.respose%>%
  mutate(gavage = gsub(" ", "", gavage)) %>%
  ggplot(aes(x=treatment, y=frac.0)) +
  geom_bar(stat="identity", 
           position="dodge", 
           aes(fill=gavage)) + 
  labs(y="Fraction Tumor Free", x="Treatment Group") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~experiment) + 
  theme_bw(base_size = 18) +
  scale_fill_viridis_d()
ggsave("../figures/Fraction-Tumor-Free.png", height= 7, width= 7)
```

# Boxplot - filtered BEWELL

```{r}
mim.boxdat$bewell.filt %>%
  ggplot(aes(x = treatment, y = tumor.volume, fill = gavage)) +
  geom_boxplot() +
  facet_wrap(. ~ patient, scales = "free_y") +
  xlab("Treatment") +
  ylab("Tumor Volume") +
  ggtitle("Mimic Bewell Samples Final Tumor Volume") +
  theme_bw() +
  scale_fill_viridis_d()

ggsave("../figures/BEWELL-filtered-boxplot.png", width = 10, height = 8)
ggsave("../figures/Fig3E.svg", width = 10, height = 8)

```
# Boxplot - anti-PD1 samples

```{r}
mim.boxdat$labelled.patients %>%
  filter(patient != "other") %>%
  filter(treatment == "Anti-PD1") %>%
  ggplot(aes(x = patient, y = tumor.volume)) +
  geom_boxplot(aes(fill = gavage)) +
  theme_bw(base_size = 18) +
  scale_fill_viridis_d() +
  labs(x = "Participant Sample",
       y = expression("Tumor volume ("~mm^3~")"),
       fill = "Gavage")

ggsave("../figures/bewell-samples_PD1-only_boxplot.png",
       height = 5, width = 7)
ggsave("../figures/Fig3H.svg",
       height = 5, width = 7)
```

# Boxplot - flo data

```{r}
mim.boxflow %>%
  ggplot(aes(x = Treatment, y = Percent)) +
  geom_boxplot(aes(fill = Gavage)) +
  facet_wrap(~Marker) +
  theme_bw(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  scale_fill_viridis_d()

ggsave("../figures/boxplot_mimic10_flow.png",
       height = 5, width = 5)

ggsave("../figures/Fig3I.svg",
       height = 5, width = 5)

```

# Heatmap - longitudinal model interaction terms

```{r}
mimic.longmods %>%
  ggplot(aes(x = `Combined ID`, y = term.adj, fill = estimate, alpha = sig.flag)) +
  geom_tile(color = "black") +
  scale_fill_viridis_c() +
  coord_fixed() +
  guides(alpha = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  labs(x = "Test Microbe (Sample ID)", y = "")
  

ggsave("../figures/bewell_heatmap_interaction.png",
       height =  6, width = 6)
ggsave("../figures/Fig3D.svg",
       height =  3, width = 6)

write_csv(mimic.longmods, 
          "../tables/Supp-Table-S4_model-summary-values.csv")
```

```{r}
mimic.longmods %>%
  filter(term.adj %in% c("Anti-PD1", "Gavage")) %>%
  mutate(Combined_ID2 = gsub(".*\\(([^)]+)\\).*", "\\1", `Combined ID`)) %>%
  mutate(Combined_ID2 = case_when(
    Combined_ID2 == "DL081" ~ "Control-NR",
    Combined_ID2 == "DL017" ~ "Control-R",
    Combined_ID2 == "Control-NR" ~ "Control-R",
    Combined_ID2 == "Control-R" ~ "Control-NR",
    TRUE ~ Combined_ID2
  )) %>%
  ggplot(aes(x = Combined_ID2, y = term.adj, fill = estimate, alpha = sig.flag)) +
  geom_tile(color = "black") +
  scale_fill_viridis(option = "magma") +
  coord_fixed() +
  guides(alpha = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 20, hjust = 1)) +
  labs(x = "Test Microbe (Sample ID)", y = "")
ggsave("../figures/Fig3D-heatmap.svg",
       height =  4, width = 8)

```



