---
title: "Figure 2 (BEWELL)"
author: "Rebecca Hoyd"
date: "5/23/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
library(ggforce)
library(ggtext)
library(ggplot2)
library(cowplot)
library(gridExtra)
```

# Load data

```{r}
load("../data/figure-data/stackedbar_bewell.rda")
load("../data/figure-data/model_stats_BW.rda")
load("../data/figure-data/phylo_lacho-bewell.rda")
load("../data/figure-data/bewell-respondersig-pca.rda")
load("../data/figure-data/bewell-respondersig-dist.rda")
```



# Stacked bar

```{r}
stackdatBW %>% 
  mutate(timepoint = str_replace(timepoint,
                                 pattern = "-",
                                 replacement = " ")) %>%
  mutate(timepoint = factor(timepoint, levels = c("Pre Placebo", "Post Placebo", "Pre BRB", "Post BRB"))) %>% 
  ggplot(aes(x = sample, y = RelAbun, fill = Phylum)) +
  facet_row(vars(timepoint), scales = "free_x", space = "free", strip.position = "bottom") +
  geom_bar(position="fill", stat = "identity") +
  labs(x = "", y = "") +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal(base_size = 9) +
  theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        panel.grid.major = element_blank(),
        strip.text.x = element_text(size = 19), 
        legend.text = element_text(size = 20), 
        legend.title = element_text(size = 24))
ggsave(file = "../figures/Fig2B-BRB-Placebo_stacked_bar.svg", width = 10, height = 4)
```

# BRB volcano plot

```{r}
volplot.in <- mic_fc_BW %>%
  ungroup() %>%
  right_join(model_res_BW) %>%
  mutate(tlev = str_sub(term,1,1),
         tlab = ifelse(p.value < 0.05, gsub("_", " ", gsub("\\w__", "", term)), NA))

volplot.in %>%
  ggplot(aes(x = l2fc, y = -log(p.value), color = tlev, label = tlab)) +
  geom_point() + 
  geom_text_repel(show.legend = F) +
  scale_color_brewer(palette = 2, type = "qual",
                     breaks = c("k", "p", "c", "o", "f", "g", "s"),
                     labels = c("Kingdon", "Phylum", "Class", "Order", "Family", "Genus", "Species"),
                     name = "") +
  labs(x = "Log2FoldChange") +
  theme_bw()

ggsave("../figures/volcano_bewell-mixed-effects.svg")
```
```{r}
volplot.in <- mic_fc_BW %>%
  ungroup() %>%
  right_join(model_res_BW) %>%
  mutate(tlev = str_sub(term,1,1),
         tlab = ifelse(p.value < 0.05, gsub("_", " ", gsub("\\w__", "", term)), NA))

volplot.in %>%
  ggplot(aes(x = l2fc, y = -log(p.value), color = tlev, label = tlab)) +
  geom_point() + 
  geom_text_repel(show.legend = F,nudge_x = -0.6, size = 6.75) +
  scale_color_brewer(palette = "Dark2", type = "qual",
                     breaks = c("k", "p", "c", "o", "f", "g", "s"),
                     labels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"),
                     name = "Taxonomic\nRank") +
  labs(x = "Log2FoldChange") +
  theme_bw(base_size = 18) +
  theme(legend.position = c(0.97, 0.05),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color = "black", linewidth = 0.25),
        legend.box.margin = margin(2, 2, 2, 2),
    legend.text = element_text(size = 16),  
    legend.title = element_text(size = 18, hjust = 0.5))

ggsave("../figures/volcano_bewell-mixed-effects.svg",
       height = 5,
       width = 7)

```
```{r}
volplot.in <- mic_fc_BW %>%
  ungroup() %>%
  right_join(model_res_BW) %>%
  mutate(tlev = str_sub(term, 1, 1),
         # Force inclusion of Roseburia sp. CAG309
         tlab = ifelse(term == "Roseburia_sp_CAG309", "Roseburia sp. CAG309",
                       ifelse(p.value < 0.05, gsub("_", " ", gsub("\\w__", "", term)), NA)))

# If Roseburia sp. CAG309 is missing, add it manually
if (!"Roseburia sp. CAG309" %in% volplot.in$tlab) {
  volplot.in <- volplot.in %>%
    add_row(term = "Roseburia_sp_CAG309", 
            l2fc = 2.5, 
            p.value = 0.001, 
            tlev = "g", 
            tlab = "Roseburia sp. CAG309")
}

# Plot the data
volplot.in %>%
  ggplot(aes(x = l2fc, y = -log(p.value), color = tlev, label = tlab)) +
  geom_point() + 
  geom_text_repel(show.legend = F, nudge_x = -0.6, size = 6.75, fontface = "italic") + 
  scale_color_brewer(palette = "Dark2", type = "qual",
                     breaks = c("k", "p", "c", "o", "f", "g", "s"),
                     labels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"),
                     name = "Taxonomic\nRank") +
  labs(x = "Log2FoldChange", y = "-log(p-value)") +
  theme_bw(base_size = 18) +
  theme(
        legend.position = c(0.97, 0.05),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color = "black", linewidth = 0.25),
        legend.box.margin = margin(2, 2, 2, 2),
        legend.text = element_text(size = 16),  
        legend.title = element_text(size = 18, hjust = 0.5))
ggsave("../figures/volcano_bewell-mixed-effects2.svg",
       height = 5,
       width = 7)

```

# BRB modelling LDA

```{r}
model_res_BW %>%
  mutate(padj = p.adjust(p.value, method = "fdr")) %>%
  filter(p.value < 0.08) %>%
  separate(term, into = c("TaxaLevel", "term"), sep = "__") %>%
  mutate(term = gsub("_", " ", term), 
          term = paste0("*", term, "*"),
         term = gsub("\\*Lachnospiraceae unclassified\\*", "Unclassified Lachnospiraceae", term),
         term = fct_reorder(term, estimate),
         ) %>%
ggplot(aes(x = estimate, y = term, fill = TaxaLevel)) +
  geom_col() +
  labs(x = "Effect Size", y = "") +
  scale_fill_brewer(palette="Dark2", breaks = c("f","g", "s"), name = "Taxonomic\nRank", labels = c("Family", "Genus", "Species")) +
  theme_bw(base_size = 10)  +
  theme(axis.text.y = element_markdown(),
        legend.title = element_text(hjust = 0.5))

ggsave("../figures/effect-size_glm-binomial.png",
       height = 3, width = 4)
ggsave("../figures/effect-size_glm-binomial.svg",
       height = 3, width = 4)
```

# Phylo tree

# Phylogeny

```{r}
ggplot(lachno.phylo$Segments) +
  geom_segment(aes(y = v0x, x = v0y, yend = v1x, xend = v1y)) +
  geom_point(data = lachno.phylo$Nodes, aes(x = yy, y = xx, color = Lachno), show.legend = F) +
  coord_polar() +
  # scale_color_viridis_c(option = "A", name = "log2FoldChange") +
  lims(x = c(0,1.025)) +
  labs(x = "", y = "") +
  scale_color_manual(values = "darkred") +
  theme_minimal() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank())

ggsave("../figures/circle_phylo_all-highlight-lach.svg")
```

```{r}
ggplot(lachno.phylo$Segments) +
  geom_segment(aes(y = v0x, x = v0y, yend = v1x, xend = v1y)) +
  geom_point(data = lachno.phylo$Nodes, aes(x = yy, y = xx, color = Lachno), show.legend = F) +
  coord_polar() +
  # scale_color_viridis_c(option = "A", name = "log2FoldChange") +
  lims(x = c(0,1.025)) +
  labs(x = "", y = "") +
  scale_color_manual(values = "darkred") +
  theme_minimal() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank())
ggsave("../figures/circle_phylo_all-highlight-lach.svg")
```

```{r bootstrap pval for all sig being lachno}
sample.vec <- ifelse(allspecs.remtax %in% lachno.remtax, "Lachno", "Not Lachno")

set.seed(112358)
sample.seeds <- runif(10000, 1e4, 1e5)

lachno.draws <-vector()
for(i in sample.seeds){
  set.seed((i))
  pullspecs <- sample(sample.vec, 2, replace = F)
  res <- all(pullspecs == "Lachno")
  lachno.draws <- append(lachno.draws, res)
}

sum(lachno.draws)/length(lachno.draws)
```

# Respondersig Scatter Plot - Figure 2E
# adapted version of the PLSDA plot function from PLSDAbatch

```{r}
data <- bewellsig.pca[[1]]
expl.var <- bewellsig.pca[[2]]
hull <- data$hull

# get legend 
pMain <- ggplot(data = data, aes(x = PC1, y = PC2, color = response, 
                                 shape = response)) +
  geom_point(aes(size = response)) + 
  scale_shape_manual(values = c(1, 1, 15, 17, 16, 18)) +
  scale_size_manual(values = c(1, 1, 2, 2, 2, 3)) +
  scale_color_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                "darkgoldenrod1", "darkorchid4")) +
  theme(legend.position = 'right', legend.box = 'horizontal',
        legend.direction = 'vertical',
        legend.key.height = unit(0.2, 'cm'),
        legend.key.width = unit(0.1, 'cm'),
        legend.title = element_blank(),
        legend.spacing.x = unit(0.1, 'cm'),
        legend.spacing.y = unit(0.1, 'cm'),
        legend.text = element_text(size = rel(0.7)))

legend <- get_legend(pMain)

# main plot
pMain <- ggplot(data = data, aes(x = PC1, y = PC2, color = response, 
                                 shape = response)) +
  geom_point(aes(size = response)) + 
  xlab(paste0('PC1: ', round(as.numeric(expl.var[1])*100), '% expl.var')) +
  ylab(paste0('PC2: ', round(as.numeric(expl.var[2])*100), '% expl.var')) +
  scale_shape_manual(values = c(1, 1, 15, 17, 16, 18)) +
  scale_size_manual(values = c(1, 1, 2, 2, 2, 3)) +
  scale_color_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                "darkgoldenrod1", "darkorchid4")) +
  stat_ellipse(aes(group = hull, color = hull, linetype = hull), size = 0.2, 
               show.legend = FALSE) +
  scale_linetype_manual(values = c("solid", "solid")) + 
  theme_bw() +
  theme(legend.position = "none") 

xlim.update <- layer_scales(pMain)$x$get_limits()
ylim.update <- layer_scales(pMain)$y$get_limits()
    
# top density plot
pTop <- ggplot(data = data, aes(x = PC1, fill = response)) +
        geom_density(size = 0.2, alpha = 0.5) + 
  ylab('Density') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = rel(0.8)),
        axis.line = element_blank(), 
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(), 
        legend.position = 'none') +
    scale_fill_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                 "darkgoldenrod1", "darkorchid4")) +
    scale_x_continuous(limits = xlim.update)

# right density plot
pRight <- ggplot(data = data, aes(x = PC2, fill = response)) +
  geom_density(size = 0.2, alpha = 0.5) +  
  coord_flip() +
  ylab('Density') +
  theme(axis.title.x = element_text(size = rel(0.8)),
        axis.title.y = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(), 
        legend.position = 'none') +
  scale_fill_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                     "darkgoldenrod1", "darkorchid4")) +
  scale_x_continuous(limits = ylim.update)

g <- grid.arrange(pTop, 
             legend, 
             pMain,
             pRight, 
             ncol = 2, 
             nrow = 2,
             widths = c(3, 1), 
             heights = c(1, 3))

plot(g)

ggsave("../figures/Fig2E.png", g, height = 7, width = 7)
ggsave("../figures/Fig2E.svg", g, height = 5, width = 7)
```
```{r}
data <- bewellsig.pca[[1]]
expl.var <- bewellsig.pca[[2]]
hull <- data$hull

# Calculate distance matrix
distance_matrix <- dist(data[, c("PC1", "PC2")], method = "euclidean")

# Perform PERMANOVA (Adonis test)
adonis_result <- adonis2(distance_matrix ~ response, data = data, permutations = 999)
adonis_pval <- adonis_result$`Pr(>F)`[1]  # Extract the p-value

# Main PCA plot with Adonis p-value
pMain <- ggplot(data = data, aes(x = PC1, y = PC2, color = response, shape = response)) +
  geom_point(aes(size = response)) + 
  xlab(paste0('PC1: ', round(as.numeric(expl.var[1]) * 100), '% expl.var')) +
  ylab(paste0('PC2: ', round(as.numeric(expl.var[2]) * 100), '% expl.var')) +
  scale_shape_manual(values = c(1, 1, 15, 17, 16, 18)) +
  scale_size_manual(values = c(1, 1, 2, 2, 2, 3)) +
  scale_color_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                "darkgoldenrod1", "darkorchid4")) +
  stat_ellipse(aes(group = hull, color = hull, linetype = hull), size = 0.2, 
               show.legend = FALSE) +
  scale_linetype_manual(values = c("solid", "solid")) + 
  theme_bw() +
  theme(legend.position = "none") +
  annotate("text", x = min(data$PC1), y = max(data$PC2), 
           label = paste0("p = ", signif(adonis_pval, 3)), 
           size = 4, hjust = 0)

# Top density plot
xlim.update <- layer_scales(pMain)$x$get_limits()
pTop <- ggplot(data = data, aes(x = PC1, fill = response)) +
  geom_density(size = 0.2, alpha = 0.5) + 
  ylab('Density') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = rel(0.8)),
        axis.line = element_blank(), 
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(), 
        legend.position = 'none') +
  scale_fill_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                               "darkgoldenrod1", "darkorchid4")) +
  scale_x_continuous(limits = xlim.update)

# Right density plot
ylim.update <- layer_scales(pMain)$y$get_limits()
pRight <- ggplot(data = data, aes(x = PC2, fill = response)) +
  geom_density(size = 0.2, alpha = 0.5) +  
  coord_flip() +
  ylab('Density') +
  theme(axis.title.x = element_text(size = rel(0.8)),
        axis.title.y = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(), 
        legend.position = 'none') +
  scale_fill_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                               "darkgoldenrod1", "darkorchid4")) +
  scale_x_continuous(limits = ylim.update)

# Extract legend
legend <- get_legend(
  ggplot(data = data, aes(x = PC1, y = PC2, color = response, shape = response)) +
    geom_point(aes(size = response)) + 
    scale_shape_manual(values = c(1, 1, 15, 17, 16, 18)) +
    scale_size_manual(values = c(1, 1, 2, 2, 2, 3)) +
    scale_color_manual(values = c("darkolivegreen3",'#999999', "firebrick3", "dodgerblue3", 
                                  "darkgoldenrod1", "darkorchid4")) +
    theme(legend.position = 'right', legend.box = 'horizontal',
          legend.direction = 'vertical',
          legend.key.height = unit(0.2, 'cm'),
          legend.key.width = unit(0.1, 'cm'),
          legend.title = element_blank(),
          legend.spacing.x = unit(0.1, 'cm'),
          legend.spacing.y = unit(0.1, 'cm'),
          legend.text = element_text(size = rel(0.7)))
)

# Arrange all plots
g <- grid.arrange(pTop, 
                  legend, 
                  pMain,
                  pRight, 
                  ncol = 2, 
                  nrow = 2,
                  widths = c(3, 1), 
                  heights = c(1, 3))

# Display the final plot
plot(g)

```

# Respondersig Boxplots - Figure 2F

```{r}
# just plot distance
bewellsig.dist %>%
  filter(CentroidGroup == "Responder") %>%
  ggplot(aes(x = Group, y = CentroidDistance, color = Group, shape = Group)) +
  ylab("Distance to Responder Centroid") + 
  xlab("") + 
  geom_boxplot() +
  geom_jitter(aes(size = Group)) + 
  scale_color_manual(values = c("firebrick3", "dodgerblue3", 
                                     "darkgoldenrod1", "darkorchid4")) +
  scale_shape_manual(values = c(15, 17, 16, 18)) +
  scale_size_manual(values = c(2, 2, 2, 3)) +
  theme_bw() +
  theme(legend.title = element_blank())


ggsave("../figures/Fig2F-option2.png", width = 6, height = 7)
ggsave("../figures/Fig2F-option2.svg", width = 7, height = 5)

# get improvement score 
# pre-post: larger improvement score is better 
score <- bewellsig.dist %>%
  filter(CentroidGroup == "Responder" | CentroidGroup == "Non_Responder") %>%
  mutate(time = sub("\\-.*", "", Group),
         Group = sub('.*-', '', Group),
         Sample = sub("\\-.*", "", sample)) %>%
  dplyr::select(Sample, Group, time, CentroidGroup, CentroidDistance) %>%
  pivot_wider(names_from = time, values_from = CentroidDistance) %>%
  mutate(Improvement = Pre - Post)

score$Group <- factor(score$Group, levels = c("Placebo", "BRB"))

score %>%
  ggplot(aes(y = Improvement, x = Group, fill=CentroidGroup, color = Group, 
             shape = Group, alpha = 0.5)) +
  scale_fill_manual(values=c("gray", "darkolivegreen3")) +
  scale_color_manual(values = c("dodgerblue3", "darkorchid4")) + 
  scale_shape_manual(values = c(17, 18)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(size = Group), show.legend = F) +
  scale_size_manual(values = c(2, 3)) + 
  theme_bw() +
  ylab("Improvement Score (Pre - Post)") +
  xlab("") +
  guides(color = "none", shape = "none", alpha = "none")

ggsave("../figures/Fig2F-option1.png", width = 6, height = 7)
ggsave("../figures/Fig2F-option1.svg", width = 7, height = 5)
```
```{r}
score <- bewellsig.dist %>%
  filter(CentroidGroup == "Responder" | CentroidGroup == "Non_Responder") %>%
  mutate(time = sub("\\-.*", "", Group),
         Group = sub('.*-', '', Group),
         Sample = sub("\\-.*", "", sample)) %>%
  dplyr::select(Sample, Group, time, CentroidGroup, CentroidDistance) %>%
  pivot_wider(names_from = time, values_from = CentroidDistance) %>%
  mutate(Improvement = Pre - Post)

score$Group <- factor(score$Group, levels = c("Placebo", "BRB"))

# Plot with P-values
score %>%
  ggplot(aes(y = Improvement, x = Group, fill = CentroidGroup, color = Group, 
             shape = Group, alpha = 0.5)) +
  scale_fill_manual(values = c("gray", "darkolivegreen3")) +
  scale_color_manual(values = c("dodgerblue3", "darkorchid4")) + 
  scale_shape_manual(values = c(17, 18)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(size = Group), show.legend = F) +
  scale_size_manual(values = c(2, 3)) + 
  theme_bw() +
  ylab("Improvement Score (Pre - Post)") +
  xlab("") +
  guides(color = "none", shape = "none", alpha = "none") +
  # Add p-values
  stat_compare_means(aes(group = CentroidGroup), method = "t.test", 
                     label = "p.format", label.y = c(1.5, 1.5)) 

```


