---
title: "scripts for PCoA plots"
author: "LN"
date: "2026-03-31"
output: html_document
--- 


```{r}
library(dplyr)
```

```{r}
bewell.relabun <- read.csv("../manuscript/data/BEWELL/RelAbun_gen.csv")
seqtab.mimic <- readRDS("../manuscript/data/mimic/2023-07-26_16S-seqtab.rds") %>%
  as.data.frame()
taxa.mimic <- readRDS("../manuscript/data/mimic/2023-07-26_16S-taxa.rds") %>%
  as.data.frame()
key <- read.csv("../manuscript/data/mimic/mimic16S-key.csv") 

taxa.long <- taxa.mimic %>%
  rownames_to_column(var="ASV") %>%
  gather(Taxonomy,Classification,-ASV) %>%
  group_by(ASV) %>% 
  mutate(Taxonomy = as.factor(Taxonomy),
         Taxonomy=fct_relevel(Taxonomy,"Kingdom","Phylum","Class","Order","Family","Genus","Species")) 

taxa.spread <- taxa.long %>%
  spread(Taxonomy,Classification) %>%
  mutate(Phylum=if_else(is.na(Phylum),paste0("p_unclassified_",Kingdom),Phylum),
         Class=if_else(is.na(Class),paste0("c_unclassified_",Phylum),Class),
         Order=if_else(is.na(Order),paste0("o_unclassified_",Class),Order),
         Family=if_else(is.na(Family),paste0("f_unclassified_",Order),Family),
         Genus=if_else(is.na(Genus),paste0("g_unclassified_",Family),Genus),
         Species=if_else(is.na(Species),paste0("s_unclassified_",Genus),Species))
```


```{r}
relabun <- seqtab.mimic %>%
  as.matrix() %>%
  make_relative() %>%
  as.data.frame() %>%
  rownames_to_column(var="sampleID")

joined <- relabun %>%
  gather(ASV,rel_abun,-sampleID) %>%
  left_join(taxa.spread,"ASV") %>%
  select(sampleID,rel_abun,Genus)

group.sum <- joined %>%
  group_by(sampleID, Genus) %>%
  summarise(genus_abundance = sum(rel_abun), count = n())

group.spread1 <- group.sum %>%
  select(sampleID,Genus,genus_abundance) %>%
  spread(Genus,genus_abundance)

#make CSV of all changes to "seqtab"
write_csv(group.spread1,"../manuscript/data/mimic/group_spread.csv")
```

